### ISSUE TITLE
add .sbxz, .sbx_affine, and .sbxreg filetypes

### ISSUE THREAD

**Issue by DavidTingley** [orena1/sbx2imagej#5]
silly historical code that changes file type rather than name....

**Comment by orena1** [comment]
very silly,
I think changing lines 
https://github.com/orena1/sbx2imagej/blob/fcc364b7225f66c901986881728d48823052f66d/sbx2imagej/sbx2imagej.py#L201-L202


to 
```python
        while not '.sbx' in self.filepath:
            self.filepath = dlg.getOpenFileName(self.Dialog, 'Choose an sbx file to load to ImageJ', self.directory, "SBX Files (*.sbx*)")[0]
```

will fix this issue, although it is a bit ugly as if the filepath has .sbx somewhere in the folderpath it will accept the file even if the extension is not correct.

**Comment by orena1** [comment]
Hi @DavidTingley, I've verified that it now also works with ant *.sbx*, I think a better methodology  for any tool that works on sbx files is not to change the filename extension ;-) @LehtinenLab
